# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 11:05
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='markdown_field',
            field=markdownx.models.MarkdownxField(default=''),
            preserve_default=False,
        ),
    ]
