# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_entry_markdown_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='text',
        ),
    ]
